// https://www.siriusxm.com/albumart/Live/Default/DefaultMDS_m_52.jpg
export enum Genre {
  pop = 'pop',
  rock = 'rock',
  electronic = 'electronic',
  hiphop = 'hiphop',
  rnb = 'rnb',
  reggae = 'reggae',
  country = 'country',
  folk = 'folk',
  jazz = 'jazz',
  christian = 'christian',
  holiday = 'holiday',
  classical = 'classical',
  latino = 'latino',
  french = 'french',
  comedy = 'comedy',
  kids = 'kids',
}

export const FriendlyGenre: Record<Genre, string> = {
  [Genre.pop]: 'Pop',
  [Genre.rock]: 'Rock',
  [Genre.electronic]: 'Electronic',
  [Genre.hiphop]: 'Hip-hop',
  [Genre.rnb]: 'R&B',
  [Genre.reggae]: 'Reggae',
  [Genre.country]: 'Country',
  [Genre.folk]: 'Folk',
  [Genre.jazz]: 'Jazz',
  [Genre.christian]: 'Christian',
  [Genre.holiday]: 'Holiday',
  [Genre.classical]: 'Classical',
  [Genre.latino]: 'Latino',
  [Genre.french]: 'French',
  [Genre.comedy]: 'Comedy',
  [Genre.kids]: 'Kids',
} as const;

export interface Channel {
  id: string;
  deeplink: string;
  name: string;
  number: number;
  genre: Genre;
  desc: string;
  playlist: string;
  allowLinkContent?: boolean;
}

export const channels: Channel[] = [
  {
    id: 'siriushits1',
    deeplink: 'SiriusXMHits1',
    number: 2,
    name: 'SiriusXM Hits 1',
    genre: Genre.pop,
    desc: 'The Most Hit-Music, featuring The Morning Mash Up, Hits 1 in Hollywood, The Weekend Countdown and Hit-Bound.',
    playlist: '6l09sdIi3KD5JduLDj4Tsb',
  },
  {
    id: '9492',
    deeplink: 'PandoraNow',
    number: 3,
    name: 'Pandora Now',
    genre: Genre.pop,
    desc: "Today's top trending hits from Pandora.",
    playlist: '3GkGF5WhFkqtlFUrU9OnDf',
  },
  {
    id: '9500',
    deeplink: 'SoulCycleRadio',
    number: 4,
    name: 'SoulCycle Radio',
    genre: Genre.pop,
    desc: 'High-energy hits, instructor guided workouts, and motivating messages for your mind, body, and Soul.',
    playlist: '035skALUZSUluHmbAt0NMY',
  },
  {
    id: '9389',
    deeplink: 'Venus',
    number: 303,
    name: 'Venus',
    genre: Genre.pop,
    desc: 'Rhythmic pop from the 2000s thru today.',
    playlist: '1y0AnhJDBSGzA8oJTIEBzU',
  },
  {
    id: '9406',
    deeplink: 'PitbullsGlobalization',
    number: 13,
    name: "Pitbull's Globalization",
    genre: Genre.pop,
    desc: 'A musical journey of Rhythm around the world. The biggest songs and the biggest DJs.',
    playlist: '1BqEMrvw8WlN4QaPNbhIHX',
  },
  {
    id: 'siriusgold',
    deeplink: '50son5',
    number: 5,
    name: '50s on 5',
    genre: Genre.pop,
    desc: "The roots of rock 'n' roll. Chuck Berry, The Coasters, Connie Francis, Little Richard, Elvis Presley, The Platters.",
    playlist: '3PYZ4AxunPFMnR8A6YCGkU',
  },
  {
    id: '60svibrations',
    deeplink: '60son6',
    number: 6,
    name: '60s on 6',
    genre: Genre.pop,
    desc: "Relive the musical revolution of the '60s.",
    playlist: '5Cq7xALOwBxguvVXTaujfY',
  },
  {
    id: 'totally70s',
    deeplink: '70son7',
    number: 7,
    name: '70s on 7',
    genre: Genre.pop,
    desc: 'Pop tunes and pop DJs from the wild and funky decade of mood rings, disco and bell bottoms!  The Super 70s!',
    playlist: '6bvogNXc9tThQdySGvkaVW',
  },
  {
    id: 'big80s',
    deeplink: '80son8',
    number: 8,
    name: '80s on 8',
    genre: Genre.pop,
    desc: "The defining hit music of the '80s. Featuring the original MTV VJs Mark Goodman, Nina Blackwood, Alan Hunter and Martha Quinn.",
    playlist: '2fUUuznL1UdtEZUftJ9tG4',
    // allowLinkContent: true,
  },
  {
    id: '8206',
    deeplink: '90son9',
    number: 9,
    name: '90s on 9',
    genre: Genre.pop,
    desc: "The defining hit music of the '90s featuring Downtown Julie Brown.",
    playlist: '46gxe8osqCP9S7KN07nx4w',
  },
  {
    id: '8208',
    deeplink: 'Pop2K',
    number: 10,
    name: 'Pop2K',
    genre: Genre.pop,
    desc: "Hear the hits from the 2000s that hit you right in the memories. It's all the songs you have a story about.",
    playlist: '7mRH4No6VXXU29FCHYMBam',
  },
  // {
  //   id: '8241',
  //   deeplink: 'KIISLosAngeles',
  //   number: 11,
  //   name: 'KIIS-Los Angeles',
  //   genre: Genre.pop,
  //   desc: "KIIS FM is LA's #1 Hit Music Station",
  //   playlist: '',
  // },
  // {
  //   id: '8242',
  //   deeplink: 'Z100NY',
  //   number: 12,
  //   name: 'Z100/NY',
  //   genre: Genre.pop,
  //   desc: "Z100 is New York's Hit Music Station",
  //   playlist: '',
  // },
  {
    id: 'coffeehouse',
    deeplink: 'TheCoffeeHouse',
    number: 14,
    name: 'The Coffee House',
    genre: Genre.pop,
    desc: 'A mix of fresh music vibes from various music styles designed to put you in relaxation mode.',
    playlist: '1pAAGsAdgQpfHBbnjlMmY9',
  },
  {
    id: 'thepulse',
    deeplink: 'ThePulse',
    number: 15,
    name: 'The Pulse',
    genre: Genre.pop,
    desc: 'Adult Pop Hits from 2010s to Today',
    playlist: '7sOw8vh5BZWGSHpif7dCKr',
  },
  {
    id: 'starlite',
    deeplink: 'TheBlend',
    number: 16,
    name: 'The Blend',
    genre: Genre.pop,
    desc: 'A bright blend of pop hits',
    playlist: '1NwzbajTT81XMuOt2DrysU',
  },
  {
    id: '9450',
    deeplink: 'PopRocks',
    number: 12,
    name: 'PopRocks',
    genre: Genre.pop,
    desc: "Rock songs that became the pop hits of the 90s and 2k. You'll know the lyrics to every song that comes on.",
    playlist: '7z5rE4CsYhLIgPKjQOz23k',
    allowLinkContent: true,
  },
  {
    id: '9446',
    deeplink: 'TheBeatlesChannel',
    number: 18,
    name: 'The Beatles Channel',
    genre: Genre.rock,
    desc: 'John, Paul, George, and Ringo changed music forever.  The songs, stories, influences and legacy of the Beatles - 24/8!',
    playlist: '51TlE2elaSXvkMwrW11tya',
  },
  {
    id: 'elvisradio',
    deeplink: 'ElvisRadio',
    number: 75,
    name: 'Elvis Radio',
    genre: Genre.rock,
    desc: "From the early years to his comeback, it's all music from Elvis Presley.",
    playlist: '7mCFJqTHrvkYA0QCiISjBU',
  },
  {
    id: 'estreetradio',
    deeplink: 'EStreetRadio',
    number: 20,
    name: 'E Street Radio',
    genre: Genre.rock,
    desc: 'Concert recordings and more from Bruce Springsteen 24/7.',
    playlist: '1gx8Hi9K4z3CtUtpqeIK0Z',
  },
  {
    id: 'undergroundgarage',
    deeplink: 'UndergroundGarage',
    number: 21,
    name: 'Underground Garage',
    genre: Genre.rock,
    desc: "The coolest rock 'n' roll records. Channel produced by Little Steven.",
    playlist: '5BWKaSyDBzj84DkLs4J9RA',
  },
  {
    id: '8370',
    deeplink: 'PearlJamRadio',
    number: 22,
    name: 'Pearl Jam Radio',
    genre: Genre.rock,
    desc: 'Studio tracks, b-sides and concert recordings from Pearl Jam 24/7.',
    playlist: '5QVE833WHUxzyZa37C2hbw',
  },
  {
    id: 'gratefuldead',
    deeplink: 'GratefulDead',
    number: 23,
    name: 'Grateful Dead',
    genre: Genre.rock,
    desc: 'Concert recordings and more from the Grateful Dead 24/7.',
    playlist: '3rhyWkXl9U2UEGaE3MOCPl',
  },
  {
    id: 'radiomargaritaville',
    deeplink: 'RadioMargaritaville',
    number: 24,
    name: 'Radio Margaritaville',
    genre: Genre.rock,
    desc: "Escape to Jimmy Buffett's Radio Margaritaville.",
    playlist: '5fK1Y4mN599opWJZcxmfcK',
  },
  {
    id: 'classicrewind',
    deeplink: 'ClassicRewind',
    number: 25,
    name: 'Classic Rewind',
    genre: Genre.rock,
    desc: "Classic Rock's second generation, with songs from the late '70s onward.",
    playlist: '0iU5vAyjvum1oh7FgLO1XZ',
  },
  {
    id: 'classicvinyl',
    deeplink: 'ClassicVinyl',
    number: 26,
    name: 'Classic Vinyl',
    genre: Genre.rock,
    desc: "Top classic rock tracks from the '60s and '70s.",
    playlist: '616YgSowjJ80HaxjgimVbh',
  },
  {
    id: 'thevault',
    deeplink: 'DeepTracks',
    number: 27,
    name: 'Deep Tracks',
    genre: Genre.rock,
    desc: "Album cuts, forgotten gems and lesser played songs from some of Classic Rock's most influential artists and essential albums",
    playlist: '0L7rkDd5o3W8uu9DsCvB9S',
  },
  {
    id: 'thespectrum',
    deeplink: 'TheSpectrum',
    number: 28,
    name: 'The Spectrum',
    genre: Genre.rock,
    desc: 'Where classic rock meets new rock.',
    playlist: '1XqYR5SX7IVzUH6OC9Zo9H',
  },
  {
    id: '9139',
    deeplink: 'PhishRadio',
    number: 29,
    name: 'Phish Radio',
    genre: Genre.rock,
    desc: 'The entire Phish multi-verse on SiriusXM.',
    playlist: '0Fqw3pQc8vBB2LVbdV4whb',
  },
  {
    id: 'jamon',
    deeplink: 'JamOn',
    number: 309,
    name: 'Jam On',
    genre: Genre.rock,
    desc: "Improvisational, eclectic rock music from today's jam bands.",
    playlist: '1Tqa4xkixbrFprRGnWYqYr',
  },
  {
    id: '8207',
    deeplink: 'TheLoft',
    number: 710,
    name: 'The Loft',
    genre: Genre.rock,
    desc: 'Adventurous music for grown-ups, from a diversity of styles and eras.',
    playlist: '2ggV8o2ZjU3j6g4Zm83g3G',
  },
  {
    id: '9407',
    deeplink: 'TomPettyRadio',
    number: 31,
    name: 'Tom Petty Radio',
    genre: Genre.rock,
    desc: "Music from Tom Petty's entire Rock & Roll Hall of Fame career, plus Tom's critically acclaimed Buried Treasure radio show.",
    playlist: '2pQrurDB4Cfdy0Bnpi6VoQ',
  },
  {
    id: '9352',
    deeplink: 'PettysBuriedTreasure',
    number: 711,
    name: "Petty's Buried Treasure",
    genre: Genre.rock,
    desc: "Tom Petty's eclectic SiriusXM radio show, Tom Petty's Buried Treasure, is now its own 24/7 commercial-free channel.",
    playlist: '1u7TBb23v0wgBvELx707AG',
  },
  {
    id: 'thebridge',
    deeplink: 'TheBridge',
    number: 17,
    name: 'The Bridge',
    genre: Genre.rock,
    desc: "Mellow classic rock and '70s folk rock.",
    playlist: '69orfEymOJESBSYJR0nJwl',
  },
  {
    id: '9506',
    deeplink: 'DaveMatthewsBandRadio',
    number: 30,
    name: 'Dave Matthews Band Radio',
    genre: Genre.rock,
    desc: 'DMB hits, fan favorites, rarities, live trax, complete concerts, and music from other artists they love.',
    playlist: '1xpfolO6nLMUV3H2vOKzzD',
  },
  {
    id: '9507',
    deeplink: 'U2XRadio',
    number: 32,
    name: 'U2 X-Radio',
    genre: Genre.rock,
    desc: 'Music and more from the Northside of Dublin and beyond. Inspiration, conversation, meditation. This is U2.',
    playlist: '3fnXrRf7zopPTTbEbX8TIA',
  },
  {
    id: '9351',
    deeplink: 'TheBeachBoysChannel',
    number: 105,
    name: 'The Beach Boys Channel',
    genre: Genre.pop,
    desc: 'The Beach Boys Channel',
    playlist: '',
  },
  {
    id: 'firstwave',
    deeplink: '1stWave',
    number: 33,
    name: '1st Wave',
    genre: Genre.rock,
    desc: 'Classic Alternative & New Wave',
    playlist: '2JVz3xpErhQUN5bBGFszNk',
  },
  {
    id: '90salternative',
    deeplink: 'Lithium',
    number: 34,
    name: 'Lithium',
    genre: Genre.rock,
    desc: "Grunge rock and '90s alternative featuring Matt Pinfield.",
    playlist: '37lAfFGYQrb0sioY7vniJU',
  },
  {
    id: 'leftofcenter',
    deeplink: 'SiriusXMU',
    number: 35,
    name: 'SiriusXMU',
    genre: Genre.rock,
    desc: 'Groundbreaking sounds, emerging artists, and indie classics.',
    playlist: '7qOY7BoRRr9BIJSUtAf80R',
  },
  {
    id: 'altnation',
    deeplink: 'AltNation',
    number: 36,
    name: 'Alt Nation',
    genre: Genre.rock,
    desc: 'The latest alternative rock releases.',
    playlist: '528bCggJBYGn1R7xW2uvPu',
  },
  {
    id: 'octane',
    deeplink: 'Octane',
    number: 37,
    name: 'Octane',
    genre: Genre.rock,
    desc: 'The cutting edge of new hard rock, featuring the next generation of headbangers destined to be headliners.',
    playlist: '65NEbKIIz4qtiDqrrIaeHz',
    allowLinkContent: true,
  },
  {
    id: 'buzzsaw',
    deeplink: 'OzzysBoneyard',
    number: 38,
    name: "Ozzy's Boneyard",
    genre: Genre.rock,
    desc: 'Hard & heavy classic rock under the influence of Ozzy Osbourne.',
    playlist: '4vbHtGPKn9htlvvobncgXM',
  },
  {
    id: 'hairnation',
    deeplink: 'HairNation',
    number: 39,
    name: 'Hair Nation',
    genre: Genre.rock,
    desc: "Hair Metal, Glam and Hard Rock from 80's Hair Bands!",
    playlist: '65fqh2mnNYROWeys9zO16j',
  },
  {
    id: 'hardattack',
    deeplink: 'LiquidMetal',
    number: 40,
    name: 'Liquid Metal',
    genre: Genre.rock,
    desc: 'The heaviest metal on or off the planet, from the ones that created it all the way to the ones that are perfecting it today.',
    playlist: '3sZL0BvJMEBpHstfccBkUR',
  },
  {
    id: '9401',
    deeplink: 'ThePrinceChannel',
    number: 333,
    name: 'The Prince Channel',
    genre: Genre.rock,
    desc: 'Prince hits, classics, B-sides & live performances',
    playlist: '',
  },
  // {
  //   id: '9353',
  //   deeplink: 'TheGrammyChannel',
  //   number: 104,
  //   name: 'The Grammy Channel',
  //   genre: Genre.pop,
  //   desc: 'Celebrating the artists, albums and songs nominated for the 63rd Annual GRAMMY Awards',
  //   playlist: '',
  // },
  // {
  //   id: '9353',
  //   deeplink: 'SiriusXM104',
  //   number: 104,
  //   name: 'SiriusXM 104',
  //   genre: Genre.pop,
  //   desc: 'Revisit the musical origins of one of the most influential figures in West Coast hip-hop with the new, limited-run 2PAC Channel.',
  //   playlist: '',
  // },
  {
    id: '9353',
    deeplink: 'BillboardTop500',
    number: 104,
    name: 'Billboard Top 500',
    genre: Genre.pop,
    desc: 'Celebrate the hottest summer hits from 1958 through 2020',
    playlist: '',
  },
  // {
  //   id: '9400',
  //   deeplink: 'TheQueenChannel',
  //   number: 35,
  //   name: 'The Queen Channel',
  //   genre: Genre.rock,
  //   desc: 'Freddie Mercury and Queen 24/7.',
  //   playlist: '',
  // },
  {
    id: '9413',
    deeplink: 'SiriusXMTurbo',
    number: 41,
    name: 'SiriusXM Turbo',
    genre: Genre.rock,
    desc: "Hard Rock from the '90s & 2000s.",
    playlist: '6F4edlU8hmKV1hjUw9bz3d',
  },
  {
    id: 'reggaerhythms',
    deeplink: 'TheJoint',
    number: 722,
    name: 'The Joint',
    genre: Genre.reggae,
    desc: 'Reggae music from its roots to today.',
    playlist: '6Enx7UKOYcjKQKWW88e35k',
  },
  {
    id: '9524',
    deeplink: 'Sound42',
    number: 42,
    name: 'Sound 42',
    genre: Genre.pop,
    desc: 'The vision of multi-platinum recording artist Drake. An exploration of boundary-pushing Hip-Hop, R&B, and global vibes.',
    playlist: '4gT2qkRlZIRJwSwvbYJUE2',
  },
  // {
  //   id: '9523',
  //   deeplink: 'BobMarleyTuffGong',
  //   number: 19,
  //   name: 'Bob Marley Tuff Gong',
  //   genre: Genre.reggae,
  //   desc:
  //     "Bob's music in one place- with rare gems, his family's recordings, and music from Tuff Gong, the family-label he founded",
  //   playlist: '',
  // },
  // {
  //   id: '9399',
  //   deeplink: 'ColdplayRadio',
  //   number: 28,
  //   name: 'Coldplay Radio',
  //   genre: Genre.rock,
  //   desc:
  //     'Coldplay hits, "live" concerts, acoustic sessions, unreleased songs, and all the influences that made them who they are today.',
  //   playlist: '',
  // },
  {
    id: '9471',
    deeplink: 'RocktheBellsRadio',
    number: 43,
    name: 'Rock the Bells Radio',
    genre: Genre.hiphop,
    desc: "LL COOL J's Rock The Bells Radio is a channel dedicated exclusively to Hip-Hop fans who want that classic Hip-Hop sound.",
    playlist: '03O42VeIOFZ4LurrqZ2l4h',
  },
  {
    id: 'hiphopnation',
    deeplink: 'HipHopNation',
    number: 44,
    name: 'Hip-Hop Nation',
    genre: Genre.hiphop,
    desc: "Today's Hip-Hop Hits-XL",
    playlist: '5YAVSfxS7XILP55Nc4b5pc',
  },
  {
    id: 'shade45',
    deeplink: 'Shade45',
    number: 45,
    name: 'Shade 45',
    genre: Genre.hiphop,
    desc: 'Shade 45, the uncensored hip-hop channel created by Eminem.',
    playlist: '3wapyDmjGSZOYWlfdg6NVf',
  },
  {
    id: 'hotjamz',
    deeplink: 'TheHeat',
    number: 46,
    name: 'The Heat',
    genre: Genre.rnb,
    desc: "What's HOT now, in R&B and Hip-Hop!",
    playlist: '77GZ4QJsqfm1rHzsAyknLz',
  },
  {
    id: '9339',
    deeplink: 'SiriusXMFLY',
    number: 47,
    name: 'SiriusXM FLY',
    genre: Genre.rnb,
    desc: "Hip-Hop and R&B from the '90s & 2000s.",
    playlist: '4niJKIE7CcGlmdFMndwSj1',
  },
  {
    id: 'heartandsoul',
    deeplink: 'HeartSoul',
    number: 48,
    name: 'Heart & Soul',
    genre: Genre.rnb,
    desc: 'R&B from today and back in the day.',
    playlist: '230p8KmI3IWcIzOzxG79O8',
  },
  {
    id: 'soultown',
    deeplink: 'SoulTown',
    number: 49,
    name: 'Soul Town',
    genre: Genre.rnb,
    desc: "Classic soul and Motown music from the '60s and '70s.",
    playlist: '5HqXfGJGjr7ttx9ZuiyTYC',
  },
  {
    id: '8228',
    deeplink: 'TheGroove',
    number: 50,
    name: 'The Groove',
    genre: Genre.rnb,
    desc: "Dance and Party grooves with Old School R&B from the '70s and '80s jams.",
    playlist: '3YMIKNXrxThChIscZSvjfV',
  },
  // {
  //   id: '9482',
  //   deeplink: 'MichaelJacksonChannel',
  //   number: 51,
  //   name: 'Michael Jackson Channel',
  //   genre: Genre.pop,
  //   desc: 'All Michael Jackson, all day',
  //   playlist: '',
  // },
  {
    id: 'thebeat',
    deeplink: 'BPM',
    number: 51,
    name: 'BPM',
    genre: Genre.electronic,
    desc: 'The biggest and emerging dance hits and remixes featuring the YouTube EDM 15.',
    playlist: '2lFDuzyw9PKxcDoeZqcZ0g',
  },
  {
    id: '9472',
    deeplink: 'DiplosRevolution',
    number: 52,
    name: "Diplo's Revolution",
    genre: Genre.electronic,
    desc: 'Future Sounds of Global Dance curated by Diplo.',
    playlist: '6jKjtV6ak9GMAX2v4HpZM3',
  },
  {
    id: 'chill',
    deeplink: 'SiriusXMChill',
    number: 53,
    name: 'SiriusXM Chill',
    genre: Genre.electronic,
    desc: 'Chill plays downtempo electronic and deep house. Music that takes you away to a relaxing poolside or chic hotel.',
    playlist: '6IkL66p1NPYQSsmTkiHxos',
  },
  {
    id: '9527',
    deeplink: 'AStateofArmin',
    number: 736,
    name: 'A State of Armin',
    genre: Genre.electronic,
    desc: 'Armin van Buuren\'s "A State of Armin" features the latest in Trance & Progressive Dance Music from superstar DJ Armin van Buuren',
    playlist: '3yzmv5OstBT33dsVGUKb8e',
  },
  {
    id: '9526',
    deeplink: 'SteveAokisRemixRadio',
    number: 735,
    name: "Steve Aoki's Remix Radio",
    genre: Genre.electronic,
    desc: 'A channel curated by DJ/Producer, Steve Aoki featuring his favorite remixes of Pop & Dance songs, and his original tracks.',
    playlist: '2h2vTRxnbUK8knXQPSHHWN',
  },
  {
    id: '9481',
    deeplink: 'StayHomeRadio',
    number: 707,
    name: 'Stay Home Radio',
    genre: Genre.pop,
    desc: 'Happy and uplifting music',
    playlist: '0a6LuTK863UaYI60ou4XRX',
  },
  {
    id: '9513',
    deeplink: 'Iceberg',
    number: 758,
    name: 'Iceberg',
    genre: Genre.rock,
    desc: "Canada's biggest rock hits from Bryan Adams and The Guess Who to Blue Rodeo and Alanis Morissette.",
    playlist: '7zTLDuEwNbKwXyER3Pk0lu',
  },
  {
    id: '9511',
    deeplink: 'Poplandia',
    number: 754,
    name: 'Poplandia',
    genre: Genre.pop,
    desc: 'Canadian Pop Hits from the 2000s and today.',
    playlist: '5c7RJiKjmSZTPvZjZGaurC',
    allowLinkContent: true,
  },
  {
    id: '9475',
    deeplink: 'BakersfieldBeat',
    number: 349,
    name: 'Bakersfield Beat',
    genre: Genre.country,
    desc: 'Music from Dwight Yoakam, and all of the artists that shaped the Bakersfield sound... and beyond.',
    playlist: '3s1WzN2vOqIXRkVywiDwuD',
  },
  {
    id: '9468',
    deeplink: 'NorthAmericana',
    number: 359,
    name: 'North Americana',
    genre: Genre.country,
    desc: 'North Americana mixes songs from the outskirts of Rock and Country and blends them with Folk artists from yesterday and today.',
    playlist: '6MnuIldyNo1L8xs5r50EV0',
  },
  // {
  //   id: '9482',
  //   deeplink: 'Calm',
  //   number: 68,
  //   name: 'Calm',
  //   genre: Genre.electronic,
  //   desc: 'Calm',
  //   playlist: '',
  // },
  {
    id: '9145',
    deeplink: 'Studio54Radio',
    number: 54,
    name: 'Studio 54 Radio',
    genre: Genre.electronic,
    desc: "Classic and Euro dance music from the '70s to the 2000s.",
    playlist: '0dtfQoGtQBqzuhFGBAJ4fH',
  },
  {
    id: '9421',
    deeplink: 'TheGarthChannel',
    number: 55,
    name: 'The Garth Channel',
    genre: Genre.country,
    desc: "The soundtrack from Garth's life - and ours!",
    playlist: '1UlODjtaFMyN0ZDeOhX1s2',
  },
  {
    id: 'newcountry',
    deeplink: 'TheHighway',
    number: 56,
    name: 'The Highway',
    genre: Genre.country,
    desc: "Today's country hits featuring Storme Warren.",
    playlist: '1BGQe15PuP4bAm9fWXY2TE',
  },
  {
    id: '9418',
    deeplink: 'NoShoesRadio',
    number: 57,
    name: 'No Shoes Radio',
    genre: Genre.country,
    desc: 'Music from & chosen by Kenny Chesney.  Never heard recordings, live concerts, unplugged moments & No Shoes Nation drop-ins.',
    playlist: '7hOnJvOYnQyoptu06wapsG',
  },
  {
    id: 'primecountry',
    deeplink: 'PrimeCountry',
    number: 58,
    name: 'Prime Country',
    genre: Genre.country,
    desc: "Country hits from the '80s and '90s.",
    playlist: '1VTLJDqdRRy2iPJYqpaBO0',
  },
  {
    id: 'theroadhouse',
    deeplink: 'WilliesRoadhouse',
    number: 59,
    name: "Willie's Roadhouse",
    genre: Genre.country,
    desc: "Classic Country from the '60s, '70s and '80s.",
    playlist: '66AbTu6qbFwgSjIz2HmmPT',
  },
  {
    id: 'outlawcountry',
    deeplink: 'OutlawCountry',
    number: 60,
    name: 'Outlaw Country',
    genre: Genre.country,
    desc: "No borders, no b.s.-from country's roots and legends to today's outsiders that just won't be fenced in.",
    playlist: '4dgqm9d8GAvrh6YycaSUdS',
  },
  {
    id: '9340',
    deeplink: 'Y2Kountry',
    number: 61,
    name: 'Y2Kountry',
    genre: Genre.country,
    desc: 'Country Hits from the 2000s',
    playlist: '4DwkilLAdrtzVAk21ITDL5',
  },
  {
    id: 'bluegrass',
    deeplink: 'BluegrassJunction',
    number: 62,
    name: 'Bluegrass Junction',
    genre: Genre.country,
    desc: 'Handmade, heartfelt bluegrass music.',
    playlist: '7AY5bUDNTD5yFbpgg2jQIW',
  },
  {
    id: 'spirit',
    deeplink: 'TheMessage',
    number: 63,
    name: 'The Message',
    genre: Genre.christian,
    desc: 'The power and positive impact of Christian pop and rock music.',
    playlist: '727rlwVoqYjJmGRtYQj61G',
  },
  {
    id: 'praise',
    deeplink: 'KirkFranklinsPraise',
    number: 64,
    name: "Kirk Franklin's Praise",
    genre: Genre.christian,
    desc: "Grammy winning icon Kirk Franklin presents the uplifting sounds of today's gospel superstars.",
    playlist: '4GbBRv0uYgbceX3SlOqbMQ',
  },
  {
    id: '8229',
    deeplink: 'enLighten',
    number: 65,
    name: 'enLighten',
    genre: Genre.christian,
    desc: "North America's southern gospel music station.",
    playlist: '7qNcz0x3GJUuNy9sOGVD3W',
  },
  {
    id: 'jazzcafe',
    deeplink: 'Watercolors',
    number: 66,
    name: 'Watercolors',
    genre: Genre.jazz,
    desc: 'Smooth and cool - a sophisticated landscape of contemporary jazz.',
    playlist: '4ncEjISbacOgI496UfM6yp',
  },
  {
    id: 'purejazz',
    deeplink: 'RealJazz',
    number: 67,
    name: 'Real Jazz',
    genre: Genre.jazz,
    desc: 'The classic sounds and styles of jazz masters, past and present.',
    playlist: '2A0MjCb3fuRepYvJKp8Aaj',
  },
  {
    id: 'spa73',
    deeplink: 'Spa',
    number: 68,
    name: 'Spa',
    genre: Genre.jazz,
    desc: 'Relaxing and soothing sounds of new age and ambient music from around the world.',
    playlist: '1Mo1PNWVfuj1KVbx3QssFb',
  },
  {
    id: '8215',
    deeplink: 'Escape',
    number: 69,
    name: 'Escape',
    genre: Genre.jazz,
    desc: 'Easy listening instrumental arrangements of familiar pop melodies!',
    playlist: '4LxzPVEhA7ewzNkpQ0xTXZ',
  },
  {
    id: 'siriusblues',
    deeplink: 'BBKingsBluesville',
    number: 74,
    name: "BB King's Bluesville",
    genre: Genre.jazz,
    desc: "B.B. King's channel for authentic blues from the past to the present.",
    playlist: '7lLZOBIR2M9dCQZL9QroMU',
  },
  {
    id: 'siriuslysinatra',
    deeplink: 'SiriuslySinatra',
    number: 71,
    name: 'Siriusly Sinatra',
    genre: Genre.jazz,
    desc: 'Music from Frank Sinatra and the greatest singers of all time.',
    playlist: '2cCyAatfLt5PyXKZVseN5W',
  },
  {
    id: 'broadwaysbest',
    deeplink: 'OnBroadway',
    number: 72,
    name: 'On Broadway',
    genre: Genre.pop,
    desc: "Show tunes from Broadway's past and present.",
    playlist: '4A39eCmMjlpLeoGRtsHJrd',
  },
  {
    id: '8205',
    deeplink: '40sJunction',
    number: 73,
    name: '40s Junction',
    genre: Genre.jazz,
    desc: "Board the Savoy Express with Big Bands, classic vocal stars and hits from the 1940s and beyond. Next stop, the '40s Junction!",
    playlist: '6YZ3adAznI9qYQWcPp2VEU',
  },
  {
    id: 'metropolitanopera',
    deeplink: 'MetOperaRadio',
    number: 355,
    name: 'Met Opera Radio',
    genre: Genre.classical,
    desc: 'Thrilling live performances from the Met, plus gems from the archives - commercial-free, around the clock.',
    playlist: '6xySQbrS8aRY9ehD53Q2Ts',
  },
  {
    id: 'symphonyhall',
    deeplink: 'SymphonyHall',
    number: 76,
    name: 'Symphony Hall',
    genre: Genre.classical,
    desc: 'Classical music by top orchestras, chamber music ensembles and instrumental soloists.',
    playlist: '7pBQrpbXOzo3jjMYhNbp4D',
  },
  {
    id: '9504',
    deeplink: 'LesTubes8090',
    number: 756,
    name: 'Les Tubes 80-90',
    genre: Genre.french,
    desc: "The biggest Francophone pop-rock hits from the 80's and 90's including Francis Cabrel and Céline Dion.",
    playlist: '',
  },
  {
    id: 'energie2',
    deeplink: 'AttitudeFranco',
    number: 759,
    name: 'Attitude Franco',
    genre: Genre.french,
    desc: 'The biggest French hits from the past 50 years.',
    playlist: '3iHrsjAvetDBjGfDKfMGZW',
  },
  {
    id: 'rumbon',
    deeplink: 'Caliente',
    number: 158,
    name: 'Caliente',
    genre: Genre.pop,
    desc: 'A red-hot Latin mix where the sounds of the Caribbean and the Americas collide. Salsa, bachata, reggaeton and Latin Urban hits.',
    playlist: '5wpJ56ypVmYrCrRbnuqkg2',
  },
  {
    id: '9420',
    deeplink: 'YachtRockRadio',
    number: 70,
    name: 'Yacht Rock Radio',
    genre: Genre.rock,
    desc: "Smooth-sailing soft rock from the late '70s and early '80s. It's the kind of rock that doesn't rock the boat!",
    playlist: '1Z4FnVPriS4iedeeCu12Zy',
  },
  {
    id: '9412',
    deeplink: 'Celebrate',
    number: 718,
    name: 'Celebrate!',
    genre: Genre.pop,
    desc: 'Happy songs to help you celebrate the fun and memorable days of your life.',
    playlist: '7phEBeyRa1S4YbOm4uafoF',
  },
  {
    id: '9415',
    deeplink: 'RoadTripRadio',
    number: 301,
    name: 'Road Trip Radio',
    genre: Genre.pop,
    desc: 'A hand-selected mix of all kinds of music sharing one goal - to make you wanna roll the windows down and turn the radio up!',
    playlist: '4v68dWIfMoln6lbcVj5t5C',
  },
  // {
  //   id: '9361',
  //   deeplink: 'Velvet',
  //   number: 304,
  //   name: 'Velvet',
  //   genre: Genre.pop,
  //   desc:
  //     "Today's strong vocalists such as Sam Smith, Josh Groban, Idina Menzel, Susan Boyle, John Legend, Adele, and Adam Lambert.",
  //   playlist: '',
  // },
  {
    id: '9502',
    deeplink: '88risingRadio',
    number: 305,
    name: '88rising Radio',
    genre: Genre.pop,
    desc: 'Only the best music from all across Asia, from K-Pop, hip-hop, RnB, and more. Curated by 88rising.',
    playlist: '7DhVuB4oEPiVqj2TAU3Gba',
  },
  {
    id: '9174',
    deeplink: 'SXMRockHallRadio',
    number: 310,
    name: 'SXM Rock Hall Radio',
    genre: Genre.rock,
    desc: 'Hear music & stories from Rock Hall inductees Buddy Holly, Beatles, Marvin Gaye, Doors, Nirvana, Pink Floyd, Prince, U2 & more.',
    playlist: '2GE5O359IReXXUpfYpBWWn',
  },
  {
    id: '9543',
    deeplink: 'AndyCohensKikiLounge',
    number: 312,
    name: "Andy Cohen's Kiki Lounge",
    genre: Genre.pop,
    desc: 'Hand-picked songs you may not know from artists Andy Cohen loves. And nightly DJ sets.',
    playlist: '29S9A3WUadj0Lm4AmUst8C',
  },
  {
    id: '9175',
    deeplink: 'RockBar',
    number: 313,
    name: 'RockBar',
    genre: Genre.rock,
    desc: "A non-stop rockin' party with sing-a-long anthems from artists like AC/DC, Lynyrd Skynyrd, Van Halen and more.",
    playlist: '6SxqNeOFBXKFwEnnmoDEHF',
  },
  {
    id: 'faction',
    deeplink: 'FACTIONPUNK',
    number: 314,
    name: 'FACTION PUNK',
    genre: Genre.rock,
    desc: "Modern Punk Rock music 24/7. Pop Punk, Hardcore, '90s Punk, Ska Punk, Thrash ...If it's MODERN PUNK, it's on Faction Punk!",
    playlist: '6cnjJcF7naSeHnqFHe0TOc',
  },
  // {
  //   id: '9176',
  //   deeplink: 'SiriusXMComesAlive',
  //   number: 316,
  //   name: 'SiriusXM Comes Alive!',
  //   genre: Genre.rock,
  //   desc: 'Hear live classic rock recordings seamlessly hand crafted, song by song.',
  //   playlist: '',
  // },
  {
    id: '9364',
    deeplink: 'SiriusXMSilk',
    number: 330,
    name: 'SiriusXM Silk',
    genre: Genre.rnb,
    desc: "Slow, mature music that you feel. Sexy, strong, soft and filled with emotion, it's not a channel-it's really a vibe.",
    playlist: '6dBIcmd2U3yRl2Vc3gzwq7',
  },
  // {
  //   id: '9219',
  //   number: 340,
  //   name: "Tiësto's Club Life Radio",
  //   genre: Genre.electronic,
  //   desc: "Tiësto's EDM Channel",
  // },
  {
    id: '9365',
    deeplink: 'Utopia',
    number: 341,
    name: 'Utopia',
    genre: Genre.electronic,
    desc: "From club anthems to guilty pop pleasures to underground classics - dance hits from the '90s & 2000s.",
    playlist: '2bYk532lMoUXg4VcC3I3sy',
  },
  {
    id: '9178',
    deeplink: 'RedWhiteBooze',
    number: 350,
    name: 'Red White & Booze',
    genre: Genre.country,
    desc: 'The music of Country-themed bars and honky tonks across America.',
    playlist: '62soMdZ52YRD6ugSAreaIK',
  },
  // {
  //   id: '8372',
  //   number: 700,
  //   name: 'Neil Diamond Radio',
  //   genre: Genre.pop,
  //   desc: 'Neil Diamond, 24/7',
  // },
  {
    id: '9404',
    deeplink: 'CarolinaShagRadio',
    number: 701,
    name: 'Carolina Shag Radio',
    genre: Genre.pop,
    desc: 'A channel dedicated to the vintage R&B sounds that have meant Beach Music in the Carolinas for decades.',
    playlist: '4iXlP6xbt6qf7JOLMHGG5b',
  },
  {
    id: '9419',
    deeplink: 'ONEderland',
    number: 702,
    name: 'ONEderland',
    genre: Genre.pop,
    desc: 'Five decades of artists who had one big hit that stood the test of time.',
    playlist: '5KbqizZWO3AQ5MsZJ6IAFD',
  },
  {
    id: '9362',
    deeplink: 'Elevations',
    number: 706,
    name: 'Elevations',
    genre: Genre.pop,
    desc: 'Piano, string and orchestral versions of Classic Rock & Pop songs, now reimagined and on one unique channel!',
    playlist: '6DbrB6P4l9rzqGLRgTkAdQ',
  },
  {
    id: '9378',
    deeplink: 'OldiesParty',
    number: 703,
    name: 'Oldies Party',
    genre: Genre.pop,
    desc: "Good Time Oldies from the '50s and '60s!  Oldies Party plays the fun hits from the dawn of rock into the Woodstock years.",
    playlist: '7l2fM13ScaBKZtgjWUUm1V',
  },
  {
    id: '9372',
    deeplink: '70s80sPop',
    number: 704,
    name: '70s/80s Pop',
    genre: Genre.pop,
    desc: "Dude! You can rock your party with these hits from the '70s & '80s. From Disco to Devo...it's Masterblaster jammin' time!",
    playlist: '45AWZ4wQotKDdIdFqHC3kw',
  },
  {
    id: '9373',
    deeplink: '80s90sPop',
    number: 705,
    name: '80s/90s Pop',
    genre: Genre.pop,
    desc: "Ya can't touch this!  Essential party hits from the Awesome '80s & the Whassup! '90s...it's Electric!",
    playlist: '4J2L5Sg2iVbDjMdiBbRNNB',
  },
  // {
  //   id: '9352',
  //   number: 712,
  //   name: 'Tom Petty\'s Buried Treasure',
  //   genre: Genre.rock,
  //   desc: 'Tom Petty’s Buried Treasure 24/7',
  // },
  // {
  //   id: '9351',
  //   deeplink: 'SiriusXM105',
  //   number: 105,
  //   name: 'SiriusXM 105',
  //   genre: Genre.rock,
  //   desc: 'SiriusXM 105',
  //   playlist: '35k8jXT3EzpadQHPitwmOH',
  // },
  {
    id: '9470',
    deeplink: 'MarkyRamonesPunkRock',
    number: 712,
    name: "Marky Ramone's Punk Rock",
    genre: Genre.rock,
    desc: "Marky Ramone's Punk Rock Blitzkrieg. Classic Punk 24/7 + Songs from Marky's record collection, rare tracks, live songs & more!",
    playlist: '1SEsnGKKVryUMOnLcKgzod',
  },
  {
    id: '9447',
    deeplink: 'TheEmoProject',
    number: 713,
    name: 'The Emo Project',
    genre: Genre.rock,
    desc: 'Throwback emo, scream-o and pop punk from the 2000s and beyond.',
    playlist: '640gJYYS9zAEOJ1EyKPNS0',
    allowLinkContent: true,
  },
  {
    id: '9451',
    deeplink: 'Indie10',
    number: 714,
    name: 'Indie 1.0',
    genre: Genre.rock,
    desc: 'First-Gen Indie Rock from college radio grads like Pavement and Pixies to early cult classics from The Strokes and Arcade Fire.',
    playlist: '5wZ20pHcjG4tdLvfd8CzIs',
  },
  {
    id: '9375',
    deeplink: 'ClassicRockParty',
    number: 715,
    name: 'Classic Rock Party',
    genre: Genre.rock,
    desc: 'This continuous Classic Rock Party never ends with a lampshade on your head.',
    playlist: '5MdHFbC0t8rDLtBnEb92JL',
  },
  {
    id: '9501',
    deeplink: 'TheTragicallyHipRadio',
    number: 757,
    name: 'The Tragically Hip Radio',
    genre: Genre.rock,
    desc: "The Tragically Hip Radio, playing music from the band's entire catalogue, interviews and more!",
    playlist: '3SgFyRmKbDcxd69f0vFnr1',
  },
  // {
  //   id: '9139',
  //   number: 716,
  //   name: 'SiriusXM Limited Edition 2',
  //   genre: Genre.rock,
  //   desc: 'Home for limited-run channels',
  // },
  // {
  //   id: '9402',
  //   deeplink: 'MilesDavisRadio',
  //   number: 719,
  //   name: 'Miles Davis Radio',
  //   genre: Genre.rock,
  //   desc: 'Limited run Feb 22 - Feb 28',
  //   playlist: '',
  // },
  {
    id: '9397',
    deeplink: 'SwaysUniverse',
    number: 720,
    name: "Sway's Universe",
    genre: Genre.hiphop,
    desc: "Sway's Universe, the Lifestyle channel created by Sway Calloway",
    playlist: '2F5WVKMzrtZsM1nkVygZ8Q',
  },
  // {
  //   id: '9398',
  //   number: 721,
  //   name: 'SiriusXM Limited Edition 4',
  //   genre: Genre.hiphop,
  //   desc: 'Home for limited-run channels XL',
  // },
  // {
  //   id: '9399',
  //   deeplink: 'ArethaFranklinChannel',
  //   number: 726,
  //   name: 'Aretha Franklin Channel',
  //   genre: Genre.rnb,
  //   desc: 'Limited run Feb 15 - Feb 21',
  //   playlist: '',
  // },
  // {
  //   id: '9400',
  //   deeplink: 'TheMotownChannel',
  //   number: 730,
  //   name: 'The Motown Channel',
  //   genre: Genre.rnb,
  //   desc: 'Limited run Feb 1 - Feb 7',
  //   playlist: '',
  // },
  {
    id: '8227',
    deeplink: 'TheVillage',
    number: 741,
    name: 'The Village',
    genre: Genre.folk,
    desc: 'Folk music from past to the present.',
    playlist: '6oBOE5aj9QN8FWHPcjO8W6',
  },
  // {
  //   id: '9401',
  //   number: 742,
  //   name: 'SiriusXM Limited Edition 7',
  //   genre: Genre.country,
  //   desc: 'Home for limited-run channels',
  // },
  // {
  //   id: '9402',
  //   number: 745,
  //   name: 'SiriusXM Limited Edition 8',
  //   genre: Genre.christian,
  //   desc: 'Home for limited-run channels',
  // },
  // {
  //   id: 'siriuspops',
  //   number: 755,
  //   name: 'SiriusXM Pops',
  //   genre: Genre.classical,
  //   desc: 'Classical Pops',
  // },
  // {
  //   id: '9404',
  //   number: 756,
  //   name: 'SiriusXM Limited Edition 10',
  //   genre: Genre.classical,
  //   desc: 'Home for limited-run channels',
  // },
  {
    id: '9186',
    deeplink: 'Aguila',
    number: 761,
    name: 'Águila',
    genre: Genre.latino,
    desc: 'Banda, Norteño, Mariachi and all the sounds of traditional Mexican music.',
    playlist: '5t8qMJHSsTqLVG1aWLGKZa',
  },
  {
    id: '9188',
    deeplink: 'Caricia',
    number: 762,
    name: 'Caricia',
    genre: Genre.latino,
    desc: 'Relive the classics from unforgettable artists in Spanish and English.',
    playlist: '3Rnbk4PvrAqfOLgGcaKuGL',
  },
  {
    id: '8225',
    deeplink: 'Viva',
    number: 763,
    name: 'Viva',
    genre: Genre.latino,
    desc: 'Playing a unique blend of romantic, rhythmic and urban pop from the biggest Latin stars from around the world. Viva-Pop de Hoy!',
    playlist: '',
  },
  {
    id: '9187',
    number: 764,
    deeplink: 'Latidos',
    name: 'Latidos',
    genre: Genre.latino,
    desc: "Romantic love songs from the '90s to today.",
    playlist: '3rpDpFMXGspNoSWTxw0K9j',
  },
  {
    id: '9185',
    number: 765,
    deeplink: 'FlowNacion',
    name: 'Flow Nación',
    genre: Genre.latino,
    desc: 'The hottest sounds in Reggaeton, Latin Hip-Hop and more!',
    playlist: '5q31zZOEYiwrHT0Y11WFsB',
  },
  {
    id: '9189',
    number: 766,
    deeplink: 'Luna',
    name: 'Luna',
    genre: Genre.latino,
    desc: 'Latin percussion and Afro Cuban rhythms blended with Jazz for a fun-filled musical journey.',
    playlist: '41bE6VN2mOfsdzA7QenDCC',
  },
  // {
  //   id: '9190',
  //   number: 767,
  //   deeplink: 'Rumbon',
  //   name: 'Rumbón',
  //   genre: Genre.latino,
  //   desc: 'Classic Salsa',
  //   playlist: '',
  // },
  {
    id: '9191',
    number: 768,
    deeplink: 'LaKueva',
    name: 'La Kueva',
    genre: Genre.latino,
    desc: "The Latin Rock and Alternative classics you know and love with today's upcoming artists.",
    playlist: '1vXaeALUVxzz3AD9CpJZlV',
  },
  {
    id: '9530',
    deeplink: 'DisneyHits',
    number: 302,
    name: 'Disney Hits',
    genre: Genre.kids,
    desc: 'All of your favorite Disney songs, from all time on one channel. Disney Hits!',
    playlist: '5EcZwzad4EL2iouLK8fyy6',
  },
  {
    id: '8216',
    deeplink: 'KidsPlaceLive',
    number: 78,
    name: 'Kids Place Live',
    genre: Genre.kids,
    desc: 'Family-friendly music, games, laughs and live shows for 24/7 kid-approved entertainment',
    playlist: '6X6E2y98ndt3HOgKRsr8iE',
  },
  {
    id: '9366',
    deeplink: 'KIDZBOPRadio',
    number: 77,
    name: 'KIDZ BOP Radio',
    genre: Genre.kids,
    desc: "It's all KIDZ BOP, all the time. Tune in for a 24/7 POP STAR Party hosted by the KIDZ BOP Kids, featuring today's biggest hits.",
    playlist: '6gMCkNNbluG8AYIyvCj281',
  },
  // Disabled 4/21/20
  // {
  //   id: 'radiodisney',
  //   deeplink: 'RadioDisney',
  //   number: 905,
  //   name: 'Radio Disney',
  //   genre: Genre.kids,
  //   desc: 'Pop Hits For The Entire Family',
  //   playlist: '',
  // },
  // {
  //   id: '9351',
  //   deeplink: 'ScreamRadio',
  //   number: 105,
  //   name: 'Scream Radio',
  //   genre: Genre.holiday,
  //   desc: '',
  //   playlist: '',
  // },
  // {
  //   id: '9349',
  //   deeplink: 'RadioHanukkah',
  //   number: 788,
  //   name: 'Radio Hanukkah',
  //   genre: Genre.holiday,
  //   desc:
  //     "Extensive collection of Hanukkah music, including contemporary, traditional and children's Hanukkah selections.",
  //   playlist: '',
  // },
  // {
  //   id: '9351',
  //   deeplink: 'NewYearsNation',
  //   number: 105,
  //   name: 'Billy Joel Channel',
  //   genre: Genre.pop,
  //   desc:
  //     "Music from Billy Joel's career plus stories behind the songs and Billy's memories and anecdotes.  Limited-run channel.",
  //   playlist: '',
  // },
  // {
  //   id: '9521',
  //   deeplink: 'JollyChristmas',
  //   number: 786,
  //   name: 'Jolly Christmas',
  //   genre: Genre.holiday,
  //   desc:
  //     'From The Chipmunks to Mariah Carey! Upbeat, holiday hits to brighten the season with positive energy to make you feel good',
  //   playlist: '',
  // },
  // {
  //   id: '9484',
  //   deeplink: 'AcousticChristmas',
  //   number: 781,
  //   name: 'Acoustic Christmas',
  //   genre: Genre.holiday,
  //   desc:
  //     '24/7 Acoustic holiday music from well-known singer/songwriters and rock bands as well as some new up & comers.',
  //   playlist: '',
  // },
  // {
  //   id: '9345',
  //   deeplink: 'CountryChristmas',
  //   number: 58,
  //   name: 'Country Christmas',
  //   genre: Genre.holiday,
  //   desc:
  //     'A wide-ranging assortment of country Christmas music, including Garth Brooks, Carrie Underwood and Lady A.',
  //   playlist: '',
  // },
  // {
  //   id: '9489',
  //   deeplink: 'ChristmasSpirit',
  //   number: 782,
  //   name: 'Christmas Spirit',
  //   genre: Genre.holiday,
  //   desc:
  //     "Christmas music from contemporary Christian artists. Where the reason for the season is not just remembered, He's celebrated!",
  //   playlist: '',
  // },
  // {
  //   id: '9346',
  //   deeplink: 'HolidaySoul',
  //   number: 49,
  //   name: 'Holiday Soul',
  //   genre: Genre.holiday,
  //   desc:
  //     "Classic Soul & Motown holiday music from the 60's along with R&B holiday music from the 70's, 80's, 90's and today",
  //   playlist: '',
  // },
  // {
  //   id: '9343',
  //   deeplink: 'Holly',
  //   number: 105,
  //   name: 'Holly',
  //   genre: Genre.holiday,
  //   desc: 'Contemporary holiday hits.',
  //   playlist: '',
  // },
  // {
  //   id: '9403',
  //   deeplink: 'JimiHendrixExperience',
  //   number: 743,
  //   name: 'Jimi Hendrix Experience',
  //   genre: Genre.rock,
  //   desc: 'Limited run Feb 8 - Feb 14',
  //   playlist: '',
  // },
  // {
  //   id: '9348',
  //   deeplink: 'Navidad',
  //   number: 787,
  //   name: 'Navidad',
  //   genre: Genre.latino,
  //   desc: 'Latin holiday music and traditional sounds.',
  //   playlist: '',
  // },
  // {
  //   id: '9483',
  //   deeplink: 'HallmarkChannelRadio',
  //   number: 70,
  //   name: 'Hallmark Channel Radio',
  //   genre: Genre.holiday,
  //   desc:
  //     'Celebrate the holidays with timeless Christmas music and carols 24/7 brought to you by your favorite Hallmark Channel stars',
  //   playlist: '',
  // },
  // {
  //   id: '9344',
  //   deeplink: 'HolidayPops',
  //   number: 784,
  //   name: 'Holiday Pops',
  //   genre: Genre.holiday,
  //   desc:
  //     'Classical Christmas carols and holiday favorites performed by the greatest classical artists of all-time.',
  //   playlist: '',
  // },
  {
    id: '9342',
    deeplink: 'HolidayTraditions',
    number: 776,
    name: 'Holiday Traditions',
    genre: Genre.holiday,
    desc: "Traditional holiday recordings from the '40s through the '60s.",
    playlist: '7FuozSBjyQN6CroiS0ftf6',
  },
  {
    id: 'siriuslove',
    deeplink: 'SiriusXMLove',
    number: 290,
    name: 'SiriusXM Love',
    genre: Genre.pop,
    desc: 'Romantic ballads and soft pop music featuring lyrics of love.',
    playlist: '4xwId52jcIgj1qGunqeELB',
  },
  // {
  //   id: '9416',
  //   deeplink: 'TheCoversChannel',
  //   number: 302,
  //   name: 'The Covers Channel',
  //   genre: Genre.pop,
  //   desc:
  //     "Artists paying tribute to their peers, cover songs from every genre of music of the past 6 decades. Including today's pop hits.",
  //   playlist: '',
  // },
  // {
  //   id: '9179',
  //   deeplink: 'KrishnaDasYogaRadio',
  //   number: 751,
  //   name: 'Krishna Das Yoga Radio',
  //   genre: Genre.pop,
  //   desc:
  //     'Music transporting listeners to a deeper place where they can quiet the mind and open the heart.',
  //   playlist: '',
  // },
  {
    id: 'siriuspops',
    deeplink: 'SiriusXMPops',
    number: 755,
    name: 'SiriusXM Pops',
    genre: Genre.classical,
    desc: "Classical Music's greatest hits -- beautiful and fun!",
    playlist: '7lp7vWfjoZDsMQEKZwyxoG',
  },
  // Disabled 4/21/20
  // {
  //   id: '9363',
  //   deeplink: 'JasonEllis',
  //   number: 791,
  //   name: 'Jason Ellis',
  //   genre: Genre.rock,
  //   desc: 'Jason Ellis Show Nonstop XL',
  //   playlist: '',
  // },
  {
    id: 'bluecollarcomedy',
    deeplink: 'ComedyRoundup',
    number: 97,
    name: 'Comedy Roundup',
    genre: Genre.comedy,
    desc: 'Jeff Foxworthy and Larry the Cable Guy host shows and curate stand-up from the best in American comedy.',
    playlist: '6k0bbGRHtyI1sgpeR3mbp8',
    allowLinkContent: true,
  },
  {
    id: '9494',
    deeplink: 'NetflixIsAJokeRadio',
    number: 93,
    name: 'Netflix Is A Joke Radio',
    genre: Genre.comedy,
    desc: "Ad-free home of the best of Netflix's standup specials and comedy talk shows, as well as original radio programming.",
    playlist: '02L5I1Ppe0Tu9PatWi4rI9',
    allowLinkContent: true,
  },
  {
    id: '9408',
    deeplink: 'ComedyGreats',
    number: 94,
    name: 'Comedy Greats',
    genre: Genre.comedy,
    desc: 'The greatest stand-up comedians of all time, featuring legends like Richard Pryor, Robin Williams, and Chris Rock.',
    playlist: '2hOkpE56YWOIhIs24BEyB6',
    allowLinkContent: true,
  },
  {
    id: '9356',
    deeplink: 'ComedyCentralRadio',
    number: 95,
    name: 'Comedy Central Radio',
    genre: Genre.comedy,
    desc: "Comedy Central's massive stand-up library.",
    playlist: '1p2gzc8DGpUccyPqJ0CqsZ',
    allowLinkContent: true,
  },
  {
    id: '9469',
    deeplink: 'KevinHartLaughOutLoud',
    number: 96,
    name: 'KevinHart Laugh Out Loud',
    genre: Genre.comedy,
    desc: 'Kevin Hart presents comedy, shows and other fun content.',
    playlist: '3m7SiQAkqg3D6qOQk9Tt2T',
    allowLinkContent: true,
  },
  {
    id: 'laughbreak',
    deeplink: 'LaughUSA',
    number: 98,
    name: 'Laugh USA',
    genre: Genre.comedy,
    desc: 'Clean stand-up from top comics like Jim Gaffigan and Jerry Seinfeld as well as classics from Bob Newhart, Steven Wright, & more',
    playlist: '7MdzZQU6pduI901klrsXL9',
    allowLinkContent: true,
  },
  {
    id: 'rawdog',
    deeplink: 'RawDogComedy',
    number: 99,
    name: 'Raw Dog Comedy',
    genre: Genre.comedy,
    desc: "Stand-up from today's up and coming comedy stars",
    playlist: '',
    allowLinkContent: true,
  },
  {
    id: '8259',
    deeplink: 'JustForLaughsCanada',
    number: 168,
    name: 'Just For Laughs Canada',
    genre: Genre.comedy,
    desc: "The spotlight is on Canada's rich pool of extraordinary uncensored Canadian comedy presented by Just For Laughs",
    playlist: '',
    allowLinkContent: true,
  },
  {
    id: '9503',
    deeplink: 'ShesSoFunny',
    number: 771,
    name: "She's So Funny",
    genre: Genre.comedy,
    desc: 'The Funniest Female Comedians.',
    playlist: '',
    allowLinkContent: true,
  },
  {
    id: '9542',
    deeplink: 'ComedyClassics',
    number: 772,
    name: 'Comedy Classics',
    genre: Genre.comedy,
    desc: 'Classic stand-up from legendary comedians of the past like Bob Newhart, Joan Rivers, Redd Foxx, and more!',
    playlist: '2CwMwZ0odR1iUjfqwixaUa',
    allowLinkContent: true,
  },
  {
    id: '8211',
    deeplink: 'Cinemagic',
    number: 750,
    name: 'Cinemagic',
    genre: Genre.classical,
    desc: 'Escape into the movies.',
    playlist: '0DuXdZ2rdffyB5v5mt32aB',
  },
  // {
  //   id: '9398',
  //   deeplink: 'Top1000Countdowns',
  //   number: 177,
  //   name: 'Top 1000 Countdowns',
  //   genre: Genre.pop,
  //   desc: 'Top 1000 Countdowns',
  //   playlist: '',
  // },
];
